# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Print branch, author, timestamp, component, and commit message
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Author: ${{ github.actor }}"
          echo "Timestamp: ${{ github.event.head_commit.timestamp }}"
          echo "Component: ${{ steps.extract_component.outputs.component }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: rm -rf node_modules
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          INPUT_STATUS: ${{ job.status }}
          INPUT_MESSAGE: |
            Branch: ${{ github.ref }}
            Author: ${{ github.actor }}
            Timestamp: ${{ github.event.head_commit.timestamp }}
            Component: ${{ steps.extract_component.outputs.component }}
            Commit Message: ${{ github.event.head_commit.message }}
